# HL7 Chemo Transformer Build Pipeline
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - hl7_chemo_transformer/*
      - shared_libs/*
      - pipeline-ado/templates/*
      - ca-certs/*

pr: none

parameters:
  - name: SEMANTIC_VERSION
    displayName: 'Semantic Version'
    type: string
    default: 'v0.1.0'

variables:
  acrName: 'uksdhcwihsharedcr'
  azureServiceConnection: 'Azure - NHSWales-DHCW-IntegrationHub-Subscription'
  POOL_NAME: 'UKS-DHCW-IH-DEV-ADOManagedPool'

stages:
  - stage: CodeQuality
    displayName: 'Code Quality & Tests'
    jobs:
      - template: templates/code-quality-template.yml
        parameters:
          appName: 'hl7_chemo_transformer'
          appDisplayName: 'Chemocare HL7 Transformer'
          pythonVersion: '3.13'
          poolName: ${{ variables.POOL_NAME }}

  - stage: BuildAndPushHL7ChemoTransformer
    displayName: 'Build and Push HL7 Chemocare Transformer'
    dependsOn: CodeQuality
    jobs:
      - template: templates/docker-build-push-template.yml
        parameters:
          jobName: 'BuildPushHL7ChemoTransformer'
          displayName: 'Build and Push HL7 Transformer'
          appName: 'chemo-hl7transformer'
          dockerfilePath: 'hl7_chemo_transformer/Dockerfile'
          buildContext: 'hl7_chemo_transformer'
          additionalContexts: 'shared_libs=shared_libs,ca-certs=ca-certs'
          acrName: $(acrName)
          azureServiceConnection: $(azureServiceConnection)
          POOL_NAME: ${{ variables.POOL_NAME }}
          SEMANTIC_VERSION: ${{ parameters.SEMANTIC_VERSION }}
