# HL7 Mock Receiver Build Pipeline
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - hl7_mock_receiver/*
      - shared_libs/*
      - pipeline-ado/templates/*
      - ca-certs/*

pr: none

parameters:
  - name: SEMANTIC_VERSION
    displayName: 'Semantic Version'
    type: string
    default: 'v0.1.0'

variables:
  acrName: 'uksdhcwihsharedcr'
  azureServiceConnection: 'Azure - NHSWales-DHCW-IntegrationHub-Subscription'
  POOL_NAME: 'UKS-DHCW-IH-DEV-ADOManagedPool'

stages:
  - stage: CodeQuality
    displayName: 'Code Quality & Tests'
    jobs:
      - template: templates/code-quality-template.yml
        parameters:
          appName: 'hl7_mock_receiver'
          appDisplayName: 'HL7 Mock Receiver'
          pythonVersion: '3.13'
          poolName: ${{ variables.POOL_NAME }}

  - stage: BuildAndPushHL7MockReceiver
    displayName: 'Build and Push HL7 Mock Receiver'
    dependsOn: CodeQuality
    jobs:
      - template: templates/docker-build-push-template.yml
        parameters:
          jobName: 'BuildPushHL7MockReceiver'
          displayName: 'Build and Push HL7 Mock Receiver'
          appName: 'hl7mockreceiver'
          dockerfilePath: 'hl7_mock_receiver/Dockerfile'
          buildContext: 'hl7_mock_receiver'
          additionalContexts: "shared_libs=shared_libs,ca-certs=ca-certs"
          acrName: $(acrName)
          azureServiceConnection: $(azureServiceConnection)
          POOL_NAME: ${{ variables.POOL_NAME }}
          SEMANTIC_VERSION: ${{ parameters.SEMANTIC_VERSION }}
