# HL7 Transformer Build Pipeline
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - hl7_phw_transformer/*
      - shared_libs/*
      - pipeline-ado/templates/*
      - ca-certs/*

pr: none

parameters:
  - name: POOL_SELECTION
    displayName: 'Select Agent Pool'
    type: string
    default: 'Azure Pipelines'
    values:
      - 'Azure Pipelines'
      - 'integration-hub-azure-build'
      - 'integration-hub-azure-build-dev'

  - name: SEMANTIC_VERSION
    displayName: 'Semantic Version'
    type: string
    default: 'v0.1.0'

variables:
  acrName: 'uksdhcwihsharedcr'
  azureServiceConnection: 'Azure - NHSWales-DHCW-IntegrationHub-Subscription'

stages:
  - stage: CodeQuality
    displayName: 'Code Quality & Tests'
    jobs:
      - template: templates/code-quality-template.yml
        parameters:
          appName: 'phw-hl7transformer'
          appDisplayName: 'Phw HL7 Transformer'
          pythonVersion: '3.13'
          poolName: ${{ parameters.POOL_SELECTION }}

  - stage: BuildAndPushPhwHL7Transformer
    displayName: 'Build and Push Phw HL7 Transformer'
    dependsOn: CodeQuality
    jobs:
      - template: templates/docker-build-push-template.yml
        parameters:
          jobName: 'BuildPushPhwHL7Transformer'
          displayName: 'Build and Push Phw HL7 Transformer'
          appName: 'phw-hl7transformer'
          dockerfilePath: 'hl7_phw_transformer/Dockerfile'
          buildContext: 'hl7_phw_transformer'
          additionalContexts: "shared_libs=shared_libs,ca-certs=ca-certs"
          acrName: $(acrName)
          azureServiceConnection: $(azureServiceConnection)
          POOL_NAME: ${{ parameters.POOL_SELECTION }}
          SEMANTIC_VERSION: ${{ parameters.SEMANTIC_VERSION }}
