trigger: none
pr: none

parameters:
  - name: selectedApp
    displayName: 'Select Application'
    type: string
    default: 'all'
    values:
      - all
      - PHW HL7Server
      - PIMS HL7Server
      - Paris HL7Server
      - Chemocare HL7Server
      - MPI HL7Server
      - HL7 Phw Transformer
      - HL7 Chemo Transformer
      - HL7 Pims Transformer
      - HL7 Sender
      - PIMS HL7 Sender
      - Chemocare HL7 Sender
      - HL7 Mock Receiver
      
variables:
  # Shared Configuration
  - name: acrName
    value: 'uksdhcwihsharedcr'
  - name: azureServiceConnectionNonProd
    value: 'Azure - NHSWales-DHCW-IntegrationHub-Subscription'
  - name: azureServiceConnectionProd
    value: 'Azure - NHSWales-DHCW-PROD-IntegrationHub-Subscription'
  - name: azureLocation
    value: 'uks'
    
  # Pool Configuration
  - name: POOL_NAME_NON_PROD
    value: 'UKS-DHCW-IH-DEV-ADOManagedPool'
  - name: POOL_NAME_PROD
    value: 'UKS-DHCW-IH-PPD-ADOManagedPool'

stages:
  # Define applications metadata inline
  - template: pipeline-ado/templates/list-app-version-dynamic-stages-template.yml
    parameters:
      selectedApp: ${{ parameters.selectedApp }}
      acrName: $(acrName)
      azureServiceConnection: $(azureServiceConnectionNonProd)
      
      # Application configurations
      appConfig:
        # HL7 Server Variants
        - name: 'PHW HL7Server'
          appImageName: 'hl7server'
          appFunctionMidfix: 'phw'
          buildPipeline: 'HL7 Server - Build'
          
        - name: 'PIMS HL7Server'
          appImageName: 'hl7server'
          appFunctionMidfix: 'pims'
          buildPipeline: 'HL7 Server - Build'
          
        - name: 'Paris HL7Server'
          appImageName: 'hl7server'
          appFunctionMidfix: 'paris'
          buildPipeline: 'HL7 Server - Build'
          
        - name: 'Chemocare HL7Server'
          appImageName: 'hl7server'
          appFunctionMidfix: 'chemo'
          buildPipeline: 'HL7 Server - Build'
          
        - name: 'MPI HL7Server'
          appImageName: 'hl7server'
          appFunctionMidfix: 'mpi'
          buildPipeline: 'HL7 Server - Build'

        # HL7 Transformer Variants
        - name: 'HL7 Phw Transformer'
          appImageName: 'phw-hl7transformer'
          appFunctionMidfix: ''
          buildPipeline: 'HL7 Phw Transformer - Build'
          
        - name: 'HL7 Chemo Transformer'
          appImageName: 'chemo-hl7transformer'
          appFunctionMidfix: ''
          buildPipeline: 'HL7 Chemo Transformer - Build'
          
        - name: 'HL7 Pims Transformer'
          appImageName: 'pims-hl7transformer'
          appFunctionMidfix: ''
          buildPipeline: 'HL7 Pims Transformer - Build'

        # HL7 Sender Variants
        - name: 'HL7 Sender'
          appImageName: 'hl7sender'
          appFunctionMidfix: ''
          buildPipeline: 'HL7 Sender - Build'
          
        - name: 'PIMS HL7 Sender'
          appImageName: 'hl7sender'
          appFunctionMidfix: 'pims'
          buildPipeline: 'HL7 Sender - Build'
          
        - name: 'Chemocare HL7 Sender'
          appImageName: 'hl7sender'
          appFunctionMidfix: 'chemo'
          buildPipeline: 'HL7 Sender - Build'

        # Mock Receiver
        - name: 'HL7 Mock Receiver'
          appImageName: 'hl7mockreceiver'
          appFunctionMidfix: ''
          buildPipeline: 'HL7 Mock Receiver - Build'

