trigger: none
pr: none

variables:
  - name: acrName
    value: 'uksdhcwihsharedcr'
  - name: repositoryName
    value: '' # optional, when empty will list tags for all repos
  - name: azureSubscription
    value: 'NHSWales-DHCW-NonProd-IntegrationHub-Subscription'

stages:
- stage: ListTags
  displayName: List ACR tags
  jobs:
  - job: list
    displayName: List tags
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      displayName: List ACR tags (Azure CLI)
      inputs:
        azureSubscription: '$(azureSubscription)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          set -euo pipefail
          # normalize registry name (allow either 'name' or 'name.azurecr.io')
          ACR_NAME="$(echo '$(acrName)' | sed 's/\.azurecr\.io$//')"
          REPOSITORY="$(repositoryName)"
          mkdir -p acr-tags

          echo "Listing tags from registry: $ACR_NAME"

          if [ -n "$REPOSITORY" ]; then
            echo "Listing tags for repository: $REPOSITORY"
            az acr repository show-tags --name "$ACR_NAME" --repository "$REPOSITORY" --output json > "acr-tags/${REPOSITORY//\//_}.json"
            echo "Wrote acr-tags/${REPOSITORY//\//_}.json"
          else
            echo "No repository specified — enumerating repositories"
            repos=$(az acr repository list --name "$ACR_NAME" --output tsv)
            if [ -z "$repos" ]; then
              echo "No repositories found in registry $ACR_NAME"
            else
              for r in $repos; do
                echo " - $r"
                az acr repository show-tags --name "$ACR_NAME" --repository "$r" --output json > "acr-tags/${r//\//_}.json" || echo "Failed to list tags for $r"
              done
              echo "Wrote tags for $(ls acr-tags | wc -l) repositories"
            fi
          fi

    - task: PublishPipelineArtifact@1
      displayName: Publish tags artifact
      inputs:
        targetPath: 'acr-tags'
        artifact: 'acr-tags'
        publishLocation: 'pipeline'
