# Alternative PR Validation Pipeline with better error handling
# This version uses bash strict mode and better error handling
trigger: none

pr:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - hl7_server/*
      - hl7_transformer/*
      - hl7_sender/*
      - shared_libs/*
      - pipeline-ado/*

parameters:
  - name: POOL_SELECTION
    displayName: 'Select Agent Pool'
    type: string
    default: 'Azure Pipelines'
    values:
      - 'Azure Pipelines'
      - 'integration-hub-azure-build'
      - 'integration-hub-azure-build-dev'

variables:
  pythonVersion: '3.13'

stages:
  - stage: PRValidation
    displayName: 'PR Code Quality & Unit Tests'
    jobs:
      - job: CodeQualityAndTests
        displayName: 'Code Quality Checks & Unit Tests'
        pool:
          ${{ if eq(parameters.POOL_SELECTION, 'Azure Pipelines') }}:
            vmImage: 'ubuntu-latest'
          ${{ else }}:
            name: ${{ parameters.POOL_SELECTION }}
        
        steps:
          - checkout: self
            displayName: 'Checkout Repository'
            fetchDepth: 1

          - task: UsePythonVersion@0
            displayName: 'Use Python $(pythonVersion)'
            inputs:
              versionSpec: '$(pythonVersion)'

          - script: |
              set -euo pipefail  # Bash strict mode
              echo "##[group]Install pipx and tools"
              python -m pip install --upgrade pip
              python -m pip install pipx
              pipx install ruff
              pipx install bandit
              pipx install mypy
              echo "##[endgroup]"
            displayName: 'Install Code Quality Tools'

          - script: |
              set -euo pipefail
              echo "##[group]Install App Dependencies"
              
              # Verify directories exist
              for app in hl7_server hl7_transformer hl7_sender; do
                if [[ ! -d "$app" ]]; then
                  echo "##[error]Directory $app not found"
                  exit 1
                fi
              done
              
              # Install shared library first (from root directory)
              echo "Installing shared library..."
              pip install -e shared_libs/message_bus_lib/
              
              # Install each app's dependencies (from their respective directories)
              echo "Installing hl7_server dependencies..."
              cd hl7_server
              pip install -r requirements.txt
              cd ..
              
              echo "Installing hl7_transformer dependencies..."
              cd hl7_transformer
              pip install -r requirements.txt
              cd ..
              
              echo "Installing hl7_sender dependencies..."
              cd hl7_sender
              pip install -r requirements.txt
              cd ..
              
              # Verify critical imports work
              python -c "import azure.servicebus; print('âœ… azure-servicebus imported successfully')"
              python -c "import hl7apy; print('âœ… hl7apy imported successfully')"
              python -c "import message_bus_lib; print('âœ… message_bus_lib imported successfully')"
              
              echo "##[section]Installed packages:"
              pip list | grep -E "(azure|hl7|message-bus)"
              echo "##[endgroup]"
            displayName: 'Install Dependencies'

          # Combined validation script for each app
          - script: |
              set -euo pipefail
              echo "##[group]Validate HL7 Server"
              cd hl7_server
              
              echo "ðŸ” Running Ruff check..."
              pipx run ruff check --output-format=github .
              
              echo "ðŸ”’ Running Bandit security scan..."
              if [[ -d "hl7_server" && -d "tests" ]]; then
                pipx run bandit -r hl7_server tests --severity-level medium
              else
                echo "##[warning]Skipping bandit - directories not found"
              fi
              
              echo "ðŸ·ï¸ Running MyPy type check..."
              if find hl7_server tests -name "*.py" -type f | head -1 > /dev/null 2>&1; then
                find hl7_server tests -name "*.py" -type f | xargs pipx run mypy --ignore-missing-imports
              else
                echo "##[warning]No Python files found for type checking"
              fi
              
              echo "ðŸ§ª Running unit tests..."
              python -m unittest discover tests -v
              
              echo "âœ… HL7 Server validation completed"
              echo "##[endgroup]"
            displayName: 'Validate HL7 Server'

          - script: |
              set -euo pipefail
              echo "##[group]Validate HL7 Transformer"
              cd hl7_transformer
              
              echo "ðŸ” Running Ruff check..."
              pipx run ruff check --output-format=github .
              
              echo "ðŸ”’ Running Bandit security scan..."
              if [[ -d "hl7_transformer" && -d "tests" ]]; then
                pipx run bandit -r hl7_transformer tests --severity-level medium
              else
                echo "##[warning]Skipping bandit - directories not found"
              fi
              
              echo "ðŸ·ï¸ Running MyPy type check..."
              if find hl7_transformer tests -name "*.py" -type f | head -1 > /dev/null 2>&1; then
                find hl7_transformer tests -name "*.py" -type f | xargs pipx run mypy --ignore-missing-imports
              else
                echo "##[warning]No Python files found for type checking"
              fi
              
              echo "ðŸ§ª Running unit tests..."
              python -m unittest discover tests -v
              
              echo "âœ… HL7 Transformer validation completed"
              echo "##[endgroup]"
            displayName: 'Validate HL7 Transformer'

          - script: |
              set -euo pipefail
              echo "##[group]Validate HL7 Sender"
              cd hl7_sender
              
              echo "ðŸ” Running Ruff check..."
              pipx run ruff check --output-format=github .
              
              echo "ðŸ”’ Running Bandit security scan..."
              if [[ -d "hl7_sender" && -d "tests" ]]; then
                pipx run bandit -r hl7_sender tests --severity-level medium
              else
                echo "##[warning]Skipping bandit - directories not found"
              fi
              
              echo "ðŸ·ï¸ Running MyPy type check..."
              if find hl7_sender tests -name "*.py" -type f | head -1 > /dev/null 2>&1; then
                find hl7_sender tests -name "*.py" -type f | xargs pipx run mypy --ignore-missing-imports
              else
                echo "##[warning]No Python files found for type checking"
              fi
              
              echo "ðŸ§ª Running unit tests..."
              python -m unittest discover tests -v
              
              echo "âœ… HL7 Sender validation completed"
              echo "##[endgroup]"
            displayName: 'Validate HL7 Sender'

          - script: |
              set -euo pipefail
              echo "##[group]Validate Shared Libraries"
              cd shared_libs/message_bus_lib
              
              echo "ðŸ” Running Ruff check..."
              pipx run ruff check --output-format=github .
              
              echo "ðŸ”’ Running Bandit security scan..."
              if [[ -d "message_bus_lib" && -d "tests" ]]; then
                pipx run bandit -r message_bus_lib tests --severity-level medium
              else
                echo "##[warning]Skipping bandit - directories not found"
              fi
              
              echo "ðŸ·ï¸ Running MyPy type check..."
              if find message_bus_lib tests -name "*.py" -type f | head -1 > /dev/null 2>&1; then
                find message_bus_lib tests -name "*.py" -type f | xargs pipx run mypy --ignore-missing-imports
              else
                echo "##[warning]No Python files found for type checking"
              fi
              
              echo "ðŸ§ª Running unit tests..."
              python -m unittest discover tests -v
              
              echo "âœ… Shared Libraries validation completed"
              echo "##[endgroup]"
            displayName: 'Validate Shared Libraries'

          # Final summary
          - script: |
              echo "##[section]ðŸŽ‰ PR Validation Summary"
              echo "âœ… Code quality checks completed for all apps"
              echo "âœ… Security scans completed for all apps"
              echo "âœ… Type checking completed for all apps"
              echo "âœ… Unit tests completed for all apps"
              echo ""
              echo "ðŸš€ All checks passed! PR is ready for review."
            displayName: 'PR Validation Summary'
