# PR Validation Pipeline using Templates
# This pipeline validates code quality, security, and tests for all apps
trigger: none

pr:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - hl7_server/*
      - hl7_transformer/*
      - hl7_sender/*
      - hl7_mock_receiver/*
      - shared_libs/*
      - pipeline-ado/*

parameters:
  - name: POOL_SELECTION
    displayName: 'Select Agent Pool'
    type: string
    default: 'Azure Pipelines'
    values:
      - 'Azure Pipelines'
      - 'integration-hub-azure-build'
      - 'integration-hub-azure-build-dev'

variables:
  pythonVersion: '3.13'

stages:
  - stage: PRValidation
    displayName: 'PR Code Quality & Unit Tests'
    jobs:
      # HL7 Server validation
      - template: templates/code-quality-template.yml
        parameters:
          appName: 'hl7_server'
          appDisplayName: 'HL7 Server'
          pythonVersion: $(pythonVersion)
          poolName: ${{ parameters.POOL_SELECTION }}

      # HL7 Transformer validation
      - template: templates/code-quality-template.yml
        parameters:
          appName: 'hl7_transformer'
          appDisplayName: 'HL7 Transformer'
          pythonVersion: $(pythonVersion)
          poolName: ${{ parameters.POOL_SELECTION }}

      # HL7 Sender validation
      - template: templates/code-quality-template.yml
        parameters:
          appName: 'hl7_sender'
          appDisplayName: 'HL7 Sender'
          pythonVersion: $(pythonVersion)
          poolName: ${{ parameters.POOL_SELECTION }}

      # HL7 Mock Receiver validation
      - template: templates/code-quality-template.yml
        parameters:
          appName: 'hl7_mock_receiver'
          appDisplayName: 'HL7 Mock Receiver'
          pythonVersion: $(pythonVersion)
          poolName: ${{ parameters.POOL_SELECTION }}

      # Shared Libraries validation
      - template: templates/code-quality-template.yml
        parameters:
          appName: 'shared_libs/message_bus_lib'
          appDisplayName: 'Shared Libraries'
          banditSourceDir: 'message_bus_lib'
          pythonVersion: $(pythonVersion)
          poolName: ${{ parameters.POOL_SELECTION }}

      # Final summary
      - job: PRSummary
        displayName: 'PR Validation Summary'
        dependsOn: 
          - CodeQuality_hl7_server
          - CodeQuality_hl7_transformer
          - CodeQuality_hl7_sender
          - CodeQuality_hl7_mock_receiver
          - CodeQuality_shared_libs_message_bus_lib
        pool:
          ${{ if eq(parameters.POOL_SELECTION, 'Azure Pipelines') }}:
            vmImage: 'ubuntu-latest'
          ${{ else }}:
            name: ${{ parameters.POOL_SELECTION }}
        steps:
          - script: |
              echo "##[section]🎉 PR Validation Summary"
              echo "✅ Code quality checks completed for all apps"
              echo "✅ Security scans completed for all apps"
              echo "✅ Type checking completed for all apps"
              echo "✅ Unit tests completed for all apps"
              echo ""
              echo "🚀 All checks passed! PR is ready for review."
            displayName: 'PR Validation Summary'
