# PR Validation Pipeline using Templates
# This pipeline validates code quality, security, and tests for all apps
trigger: none

pr:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - hl7_server/*
      - hl7_phw_transformer/*
      - hl7_sender/*
      - hl7_mock_receiver/*
      - hl7_chemo_transformer/*
      - hl7_pims_transformer/*
      - shared_libs/*
      - pipeline-ado/*

parameters:
  - name: POOL_SELECTION
    displayName: 'Select Agent Pool'
    type: string
    default: 'Azure Pipelines'
    values:
      - 'Azure Pipelines'
      - 'UKS-DHCW-IH-DEV-ADOManagedPool'
      - 'UKS-DHCW-IH-TST-ADOManagedPool'

variables:
  pythonVersion: '3.13'

stages:
  - stage: PRValidation
    displayName: 'PR Code Quality & Unit Tests'
    jobs:
      # HL7 Server validation
      - template: templates/code-quality-template.yml
        parameters:
          appName: 'hl7_server'
          appDisplayName: 'HL7 Server'
          pythonVersion: $(pythonVersion)
          poolName: ${{ parameters.POOL_SELECTION }}

      # HL7 Transformer validation
      - template: templates/code-quality-template.yml
        parameters:
          appName: 'hl7_phw_transformer'
          appDisplayName: 'HL7 Transformer'
          pythonVersion: $(pythonVersion)
          poolName: ${{ parameters.POOL_SELECTION }}

      # HL7 Sender validation
      - template: templates/code-quality-template.yml
        parameters:
          appName: 'hl7_sender'
          appDisplayName: 'HL7 Sender'
          pythonVersion: $(pythonVersion)
          poolName: ${{ parameters.POOL_SELECTION }}

      # HL7 Mock Receiver validation
      - template: templates/code-quality-template.yml
        parameters:
          appName: 'hl7_mock_receiver'
          appDisplayName: 'HL7 Mock Receiver'
          pythonVersion: $(pythonVersion)
          poolName: ${{ parameters.POOL_SELECTION }}

      # HL7 Chemo Transformer validation
      - template: templates/code-quality-template.yml
        parameters:
          appName: 'hl7_chemo_transformer'
          appDisplayName: 'HL7 Chemo Transformer'
          pythonVersion: $(pythonVersion)
          poolName: ${{ parameters.POOL_SELECTION }}

      # HL7 PIMS Transformer validation
      - template: templates/code-quality-template.yml
        parameters:
          appName: 'hl7_pims_transformer'
          appDisplayName: 'HL7 PIMS Transformer'
          pythonVersion: $(pythonVersion)
          poolName: ${{ parameters.POOL_SELECTION }}

      # Shared Libraries validation
      - template: templates/code-quality-template.yml
        parameters:
          appName: 'shared_libs/message_bus_lib'
          appDisplayName: 'Message Bus Library'
          banditSourceDir: 'message_bus_lib'
          pythonVersion: $(pythonVersion)
          poolName: ${{ parameters.POOL_SELECTION }}

      - template: templates/code-quality-template.yml
        parameters:
          appName: 'shared_libs/event_logger_lib'
          appDisplayName: 'Event Logger Library'
          banditSourceDir: 'event_logger_lib'
          pythonVersion: $(pythonVersion)
          poolName: ${{ parameters.POOL_SELECTION }}

      - template: templates/code-quality-template.yml
        parameters:
          appName: 'shared_libs/health_check_lib'
          appDisplayName: 'Health Check Library'
          banditSourceDir: 'health_check_lib'
          pythonVersion: $(pythonVersion)
          poolName: ${{ parameters.POOL_SELECTION }}

      - template: templates/code-quality-template.yml
        parameters:
          appName: 'shared_libs/hl7_validation'
          appDisplayName: 'HL7 Validation Library'
          banditSourceDir: 'hl7_validation'
          pythonVersion: $(pythonVersion)
          poolName: ${{ parameters.POOL_SELECTION }}

      - template: templates/code-quality-template.yml
        parameters:
          appName: 'shared_libs/processor_manager_lib'
          appDisplayName: 'Processor Manager Library'
          banditSourceDir: 'processor_manager_lib'
          pythonVersion: $(pythonVersion)
          poolName: ${{ parameters.POOL_SELECTION }}
