# Main pipeline file (azure-pipelines.yml)
trigger: none
pr: none

parameters:
  - name: POOL_SELECTION
    displayName: 'Select Agent Pool'
    type: string
    default: 'Azure Pipelines'
    values:
      - 'Azure Pipelines'
      - 'integration-hub-azure-build'
      - 'inegration-hub-azure-build-dev'

variables:
  acrName: 'uksdhcwihsharedcr'
  azureServiceConnection: 'Azure - NHSWales-DHCW-IntegrationHub-Subscription'
  azureLocation: 'uks'
  hl7ServerPipelineName: 'HL7 Server - Build'
  hl7TransformerPipelineName: 'HL7 Transformer - Build'
  hl7ChemoTransformerPipelineName: 'HL7 Chemo Transformer - Build'
  hl7PimsTransformerPipelineName: 'HL7 Pims Transformer - Build'
  hl7SenderPipelineName: 'HL7 Sender - Build'
  hl7MockReceiverPipelineName: 'HL7 Mock Receiver - Build'

resources:
  pipelines:
    - pipeline: 'HL7 Server - Build'
      source: 'HL7 Server - Build'
      trigger: none
    - pipeline: 'HL7 Transformer - Build'
      source: 'HL7 Transformer - Build'
      trigger: none
    - pipeline: 'HL7 Chemo Transformer - Build'
      source: 'HL7 Chemo Transformer - Build'
      trigger: none
    - pipeline: 'HL7 Pims Transformer - Build'
      source: 'HL7 Pims Transformer - Build'
      trigger: none
    - pipeline: 'HL7 Sender - Build'
      source: 'HL7 Sender - Build'
      trigger: none
    - pipeline: 'HL7 Mock Receiver - Build'
      source: 'HL7 Mock Receiver - Build'
      trigger: none

stages:
  - stage: ReleasePHWHL7ServerDev
    displayName: 'Release App PHW HL7Server - Dev'
    jobs:
      - template: templates/release-container-app-template.yml
        parameters:
          jobName: 'ReleasePHWAppHL7ServerDev'
          displayName: 'Release App PHW HL7Server - Dev'
          appName: 'hl7server'
          appFunctionMidfix: 'phw'
          resourceGroupName: 'UK-South-DHCW-IntHub-DEV-RG'
          azureLocation: $(azureLocation)
          environment: 'dev'
          acrName: $(acrName)
          azureServiceConnection: $(azureServiceConnection)
          POOL_NAME: ${{ parameters.POOL_SELECTION }}
          resourcePipelineName: ${{ variables.hl7ServerPipelineName }}

  - stage: ReleasePIMSHL7ServerDev
    displayName: 'Release App PIMS HL7Server - Dev'
    jobs:
      - template: templates/release-container-app-template.yml
        parameters:
          jobName: 'ReleasePIMSAppHL7ServerDev'
          displayName: 'Release App PIMS HL7Server - Dev'
          appName: 'hl7server'
          appFunctionMidfix: 'pims'
          resourceGroupName: 'UK-South-DHCW-IntHub-DEV-RG'
          azureLocation: $(azureLocation)
          environment: 'dev'
          acrName: $(acrName)
          azureServiceConnection: $(azureServiceConnection)
          POOL_NAME: ${{ parameters.POOL_SELECTION }}
          resourcePipelineName: ${{ variables.hl7ServerPipelineName }}

  - stage: ReleaseParisHL7ServerDev
    displayName: 'Release App Paris HL7Server - Dev'
    jobs:
      - template: templates/release-container-app-template.yml
        parameters:
          jobName: 'ReleaseParisAppHL7ServerDev'
          displayName: 'Release App Paris HL7Server - Dev'
          appName: 'hl7server'
          appFunctionMidfix: 'paris'
          resourceGroupName: 'UK-South-DHCW-IntHub-DEV-RG'
          azureLocation: $(azureLocation)
          environment: 'dev'
          acrName: $(acrName)
          azureServiceConnection: $(azureServiceConnection)
          POOL_NAME: ${{ parameters.POOL_SELECTION }}
          resourcePipelineName: ${{ variables.hl7ServerPipelineName }}

  - stage: ReleaseChemocareHL7ServerDev
    displayName: 'Release App Chemocare HL7Server - Dev'
    jobs:
      - template: templates/release-container-app-template.yml
        parameters:
          jobName: 'ReleaseChemocareAppHL7ServerDev'
          displayName: 'Release App Chemocare HL7Server - Dev'
          appName: 'hl7server'
          appFunctionMidfix: 'chemo'
          resourceGroupName: 'UK-South-DHCW-IntHub-DEV-RG'
          azureLocation: $(azureLocation)
          environment: 'dev'
          acrName: $(acrName)
          azureServiceConnection: $(azureServiceConnection)
          POOL_NAME: ${{ parameters.POOL_SELECTION }}
          resourcePipelineName: ${{ variables.hl7ServerPipelineName }}

  - stage: ReleaseHL7TransformerDev
    displayName: 'Release App HL7Transformer - Dev'
    jobs:
      - template: templates/release-container-app-template.yml
        parameters:
          jobName: 'ReleaseAppHL7TransformerDev'
          displayName: 'Release App HL7Transformer - Dev'
          appName: 'hl7transformer'
          appFunctionMidfix: ''
          resourceGroupName: 'UK-South-DHCW-IntHub-DEV-RG'
          azureLocation: $(azureLocation)
          environment: 'dev'
          acrName: $(acrName)
          azureServiceConnection: $(azureServiceConnection)
          POOL_NAME: ${{ parameters.POOL_SELECTION }}
          resourcePipelineName: ${{ variables.hl7TransformerPipelineName }}
  
  - stage: ReleasePIMSHL7TransformerDev
    displayName: 'Release App PIMS HL7Transformer - Dev'
    jobs:
      - template: templates/release-container-app-template.yml
        parameters:
          jobName: 'ReleaseAppPIMSHL7TransformerDev'
          displayName: 'Release App PIMS HL7Transformer - Dev'
          appName: 'hl7transformer'
          appFunctionMidfix: 'pims'
          resourceGroupName: 'UK-South-DHCW-IntHub-DEV-RG'
          azureLocation: $(azureLocation)
          environment: 'dev'
          acrName: $(acrName)
          azureServiceConnection: $(azureServiceConnection)
          POOL_NAME: ${{ parameters.POOL_SELECTION }}
          resourcePipelineName: ${{ variables.hl7PimsTransformerPipelineName }}

  - stage: ReleaseHL7ChemoTransformerDev
    displayName: 'Release App HL7ChemoTransformer - Dev'
    jobs:
      - template: templates/release-container-app-template.yml
        parameters:
          jobName: 'ReleaseAppHL7ChemoTransformerDev'
          displayName: 'Release App HL7ChemoTransformer - Dev'
          appName: 'hl7chemotransformer'
          appFunctionMidfix: ''
          resourceGroupName: 'UK-South-DHCW-IntHub-DEV-RG'
          azureLocation: $(azureLocation)
          environment: 'dev'
          acrName: $(acrName)
          azureServiceConnection: $(azureServiceConnection)
          POOL_NAME: ${{ parameters.POOL_SELECTION }}
          resourcePipelineName: ${{ variables.hl7ChemoTransformerPipelineName }}

  - stage: ReleaseHL7SenderDev
    displayName: 'Release App HL7Sender - Dev'
    jobs:
      - template: templates/release-container-app-template.yml
        parameters:
          jobName: 'ReleaseAppHL7SenderDev'
          displayName: 'Release App HL7Sender - Dev'
          appName: 'hl7sender'
          appFunctionMidfix: ''
          resourceGroupName: 'UK-South-DHCW-IntHub-DEV-RG'
          azureLocation: $(azureLocation)
          environment: 'dev'
          acrName: $(acrName)
          azureServiceConnection: $(azureServiceConnection)
          POOL_NAME: ${{ parameters.POOL_SELECTION }}
          resourcePipelineName: ${{ variables.hl7SenderPipelineName }}

  - stage: ReleasePIMSHL7SenderDev
    displayName: 'Release App PIMS HL7Sender - Dev'
    jobs:
      - template: templates/release-container-app-template.yml
        parameters:
          jobName: 'ReleasePIMSAppHL7SenderDev'
          displayName: 'Release App PIMS HL7Sender - Dev'
          appName: 'hl7sender'
          appFunctionMidfix: 'pims'
          resourceGroupName: 'UK-South-DHCW-IntHub-DEV-RG'
          azureLocation: $(azureLocation)
          environment: 'dev'
          acrName: $(acrName)
          azureServiceConnection: $(azureServiceConnection)
          POOL_NAME: ${{ parameters.POOL_SELECTION }}
          resourcePipelineName: ${{ variables.hl7SenderPipelineName }}

  - stage: ReleaseChemocareHL7SenderDev
    displayName: 'Release App Chemocare HL7Sender - Dev'
    jobs:
      - template: templates/release-container-app-template.yml
        parameters:
          jobName: 'ReleaseChemocareAppHL7SenderDev'
          displayName: 'Release App Chemocare HL7Sender - Dev'
          appName: 'hl7sender'
          appFunctionMidfix: 'chemo'
          resourceGroupName: 'UK-South-DHCW-IntHub-DEV-RG'
          azureLocation: $(azureLocation)
          environment: 'dev'
          acrName: $(acrName)
          azureServiceConnection: $(azureServiceConnection)
          POOL_NAME: ${{ parameters.POOL_SELECTION }}
          resourcePipelineName: ${{ variables.hl7SenderPipelineName }}

  - stage: ReleaseHL7MockReceiverDev
    displayName: 'Release App HL7MockReceiver - Dev'
    jobs:
      - template: templates/release-container-app-template.yml
        parameters:
          jobName: 'ReleaseAppHL7MockReceiverDev'
          displayName: 'Release App HL7MockReceiver - Dev'
          appName: 'hl7mockreceiver'
          appFunctionMidfix: ''
          resourceGroupName: 'UK-South-DHCW-IntHub-DEV-RG'
          azureLocation: $(azureLocation)
          environment: 'dev'
          acrName: $(acrName)
          azureServiceConnection: $(azureServiceConnection)
          POOL_NAME: ${{ parameters.POOL_SELECTION }}
          resourcePipelineName: ${{ variables.hl7MockReceiverPipelineName }}

  - stage: ReleasePHWHL7ServerTest
    displayName: 'Release App PHW HL7Server - Test'
    dependsOn: ReleasePHWHL7ServerDev
    jobs:
      - template: templates/release-container-app-template.yml
        parameters:
          jobName: 'ReleaseAppPHWHL7ServerTest'
          displayName: 'Release App PHW HL7Server - Test'
          appName: 'hl7server'
          appFunctionMidfix: 'phw'
          resourceGroupName: 'UK-South-DHCW-IntHub-TST-RG'
          azureLocation: $(azureLocation)
          environment: 'tst'
          acrName: $(acrName)
          azureServiceConnection: $(azureServiceConnection)
          POOL_NAME: ${{ parameters.POOL_SELECTION }}
          resourcePipelineName: ${{ variables.hl7ServerPipelineName }}

  - stage: ReleasePIMSHL7ServerTest
    displayName: 'Release App PIMS HL7Server - Test'
    dependsOn: ReleasePIMSHL7ServerDev
    jobs:
      - template: templates/release-container-app-template.yml
        parameters:
          jobName: 'ReleaseAppPIMSHL7ServerTest'
          displayName: 'Release App PIMS HL7Server - Test'
          appName: 'hl7server'
          appFunctionMidfix: 'pims'
          resourceGroupName: 'UK-South-DHCW-IntHub-TST-RG'
          azureLocation: $(azureLocation)
          environment: 'tst'
          acrName: $(acrName)
          azureServiceConnection: $(azureServiceConnection)
          POOL_NAME: ${{ parameters.POOL_SELECTION }}
          resourcePipelineName: ${{ variables.hl7ServerPipelineName }}

  - stage: ReleaseParisHL7ServerTest
    displayName: 'Release App Paris HL7Server - Test'
    dependsOn: ReleaseParisHL7ServerDev
    jobs:
      - template: templates/release-container-app-template.yml
        parameters:
          jobName: 'ReleaseParisAppHL7ServerTest'
          displayName: 'Release App Paris HL7Server - Test'
          appName: 'hl7server'
          appFunctionMidfix: 'paris'
          resourceGroupName: 'UK-South-DHCW-IntHub-TST-RG'
          azureLocation: $(azureLocation)
          environment: 'tst'
          acrName: $(acrName)
          azureServiceConnection: $(azureServiceConnection)
          POOL_NAME: ${{ parameters.POOL_SELECTION }}
          resourcePipelineName: ${{ variables.hl7ServerPipelineName }}

  - stage: ReleaseChemocareHL7ServerTest
    displayName: 'Release App Chemocare HL7Server - Test'
    dependsOn: ReleaseChemocareHL7ServerDev
    jobs:
      - template: templates/release-container-app-template.yml
        parameters:
          jobName: 'ReleaseChemocareAppHL7ServerTest'
          displayName: 'Release App Chemocare HL7Server - Test'
          appName: 'hl7server'
          appFunctionMidfix: 'chemo'
          resourceGroupName: 'UK-South-DHCW-IntHub-TST-RG'
          azureLocation: $(azureLocation)
          environment: 'tst'
          acrName: $(acrName)
          azureServiceConnection: $(azureServiceConnection)
          POOL_NAME: ${{ parameters.POOL_SELECTION }}
          resourcePipelineName: ${{ variables.hl7ServerPipelineName }}

  - stage: ReleaseHL7TransformerTest
    displayName: 'Release App HL7Transformer - Test'
    dependsOn: ReleaseHL7TransformerDev
    jobs:
      - template: templates/release-container-app-template.yml
        parameters:
          jobName: 'ReleaseAppHL7TransformerTest'
          displayName: 'Release App HL7Transformer - Test'
          appName: 'hl7transformer'
          appFunctionMidfix: ''
          resourceGroupName: 'UK-South-DHCW-IntHub-TST-RG'
          azureLocation: $(azureLocation)
          environment: 'tst'
          acrName: $(acrName)
          azureServiceConnection: $(azureServiceConnection)
          POOL_NAME: ${{ parameters.POOL_SELECTION }}
          resourcePipelineName: ${{ variables.hl7TransformerPipelineName }}

  - stage: ReleasePIMSHL7TransformerTest
    displayName: 'Release App PIMS HL7Transformer - Test'
    dependsOn: ReleasePIMSHL7TransformerDev
    jobs:
      - template: templates/release-container-app-template.yml
        parameters:
          jobName: 'ReleaseAppPIMSHL7TransformerTest'
          displayName: 'Release App PIMS HL7Transformer - Test'
          appName: 'hl7transformer'
          appFunctionMidfix: 'pims'
          resourceGroupName: 'UK-South-DHCW-IntHub-TST-RG'
          azureLocation: $(azureLocation)
          environment: 'tst'
          acrName: $(acrName)
          azureServiceConnection: $(azureServiceConnection)
          POOL_NAME: ${{ parameters.POOL_SELECTION }}
          resourcePipelineName: ${{ variables.hl7PimsTransformerPipelineName }}

  - stage: ReleaseHL7ChemoTransformerTest
    displayName: 'Release App HL7ChemoTransformer - Test'
    dependsOn: ReleaseHL7ChemoTransformerDev
    jobs:
      - template: templates/release-container-app-template.yml
        parameters:
          jobName: 'ReleaseAppHL7ChemoTransformerTest'
          displayName: 'Release App HL7ChemoTransformer - Test'
          appName: 'hl7chemotransformer'
          appFunctionMidfix: ''
          resourceGroupName: 'UK-South-DHCW-IntHub-TST-RG'
          azureLocation: $(azureLocation)
          environment: 'tst'
          acrName: $(acrName)
          azureServiceConnection: $(azureServiceConnection)
          POOL_NAME: ${{ parameters.POOL_SELECTION }}
          resourcePipelineName: ${{ variables.hl7ChemoTransformerPipelineName }}

  - stage: ReleaseHL7SenderTest
    displayName: 'Release App HL7Sender - Test'
    dependsOn: ReleaseHL7SenderDev
    jobs:
      - template: templates/release-container-app-template.yml
        parameters:
          jobName: 'ReleaseAppHL7SenderTest'
          displayName: 'Release App HL7Sender - Test'
          appName: 'hl7sender'
          appFunctionMidfix: ''
          resourceGroupName: 'UK-South-DHCW-IntHub-TST-RG'
          azureLocation: $(azureLocation)
          environment: 'tst'
          acrName: $(acrName)
          azureServiceConnection: $(azureServiceConnection)
          POOL_NAME: ${{ parameters.POOL_SELECTION }}
          resourcePipelineName: ${{ variables.hl7SenderPipelineName }}

  - stage: ReleasePIMSHL7SenderTest
    displayName: 'Release App PIMS HL7Sender - Test'
    dependsOn: ReleasePIMSHL7SenderDev
    jobs:
      - template: templates/release-container-app-template.yml
        parameters:
          jobName: 'ReleasePIMSAppHL7SenderTest'
          displayName: 'Release App PIMS HL7Sender - Test'
          appName: 'hl7sender'
          appFunctionMidfix: 'pims'
          resourceGroupName: 'UK-South-DHCW-IntHub-TST-RG'
          azureLocation: $(azureLocation)
          environment: 'tst'
          acrName: $(acrName)
          azureServiceConnection: $(azureServiceConnection)
          POOL_NAME: ${{ parameters.POOL_SELECTION }}
          resourcePipelineName: ${{ variables.hl7SenderPipelineName }}

  - stage: ReleaseChemocareHL7SenderTest
    displayName: 'Release App Chemocare HL7Sender - Test'
    dependsOn: ReleaseChemocareHL7SenderDev
    jobs:
      - template: templates/release-container-app-template.yml
        parameters:
          jobName: 'ReleaseChemocareAppHL7SenderTest'
          displayName: 'Release App Chemocare HL7Sender - Test'
          appName: 'hl7sender'
          appFunctionMidfix: 'chemo'
          resourceGroupName: 'UK-South-DHCW-IntHub-TST-RG'
          azureLocation: $(azureLocation)
          environment: 'tst'
          acrName: $(acrName)
          azureServiceConnection: $(azureServiceConnection)
          POOL_NAME: ${{ parameters.POOL_SELECTION }}
          resourcePipelineName: ${{ variables.hl7SenderPipelineName }}
