# Improved Release Pipeline with Dynamic Stage Generation
# This pipeline uses configuration files and loops to reduce repetition

trigger: none
pr: none

parameters:
  - name: selectedApps
    displayName: 'Select Applications (comma-separated, or "all")'
    type: string
    default: 'all'
    # Examples:
    # - "all" = deploy all applications
    # - "PHW HL7Server" = deploy single app
    # - "PHW HL7Server,PIMS HL7Server,HL7 Sender" = deploy multiple apps
      
  - name: selectedEnvironments
    displayName: 'Select Environments (comma-separated, or "all")'
    type: string
    default: 'all'
    # Examples:
    # - "all" = deploy to all environments (with dependencies)
    # - "dev" = deploy to dev only
    # - "dev,dte,tst" = deploy to dev, dte, and tst (with dependencies between them)
    # - "tst,ppd" = deploy to tst and ppd only (no dependencies)
    
  - name: maintainDependencies
    displayName: 'Maintain environment dependencies? (only for multiple environments)'
    type: boolean
    default: false
    # true = enforce dev→dte→tst→ppd→prd chain (only if those envs are selected)
    # false = deploy to selected environments independently (parallel deployment)

variables:
  # Shared Configuration
  - name: acrName
    value: 'uksdhcwihsharedcr'
  - name: azureServiceConnection
    value: 'Azure - NHSWales-DHCW-IntegrationHub-Subscription'
  - name: azureLocation
    value: 'uks'
    
  # Pool Configuration
  - name: POOL_NAME_NON_PROD
    value: 'UKS-DHCW-IH-DEV-ADOManagedPool'
  - name: POOL_NAME_PROD
    value: 'UKS-DHCW-IH-PPD-ADOManagedPool'

resources:
  pipelines:
    - pipeline: 'HL7 Server - Build'
      source: 'HL7 Server - Build'
      trigger: none
    - pipeline: 'HL7 Phw Transformer - Build'
      source: 'HL7 Phw Transformer - Build'
      trigger: none
    - pipeline: 'HL7 Chemo Transformer - Build'
      source: 'HL7 Chemo Transformer - Build'
      trigger: none
    - pipeline: 'HL7 Pims Transformer - Build'
      source: 'HL7 Pims Transformer - Build'
      trigger: none
    - pipeline: 'HL7 Sender - Build'
      source: 'HL7 Sender - Build'
      trigger: none
    - pipeline: 'HL7 Mock Receiver - Build'
      source: 'HL7 Mock Receiver - Build'
      trigger: none

stages:
  # Define applications metadata inline (can be moved to a separate file later)
  - template: templates/dynamic-stages-template.yml
    parameters:
      selectedApps: ${{ parameters.selectedApps }}
      selectedEnvironments: ${{ parameters.selectedEnvironments }}
      maintainDependencies: ${{ parameters.maintainDependencies }}
      azureLocation: $(azureLocation)
      acrName: $(acrName)
      azureServiceConnection: $(azureServiceConnection)
      
      # Application configurations
      appConfig:
        # HL7 Server Variants
        - name: 'PHW HL7Server'
          appName: 'hl7server'
          appFunctionMidfix: 'phw'
          buildPipeline: 'HL7 Server - Build'
          
        - name: 'PIMS HL7Server'
          appName: 'hl7server'
          appFunctionMidfix: 'pims'
          buildPipeline: 'HL7 Server - Build'
          
        - name: 'Paris HL7Server'
          appName: 'hl7server'
          appFunctionMidfix: 'paris'
          buildPipeline: 'HL7 Server - Build'
          
        - name: 'Chemocare HL7Server'
          appName: 'hl7server'
          appFunctionMidfix: 'chemo'
          buildPipeline: 'HL7 Server - Build'
          
        - name: 'MPI HL7Server'
          appName: 'hl7server'
          appFunctionMidfix: 'mpi'
          buildPipeline: 'HL7 Server - Build'

        # HL7 Transformer Variants
        - name: 'HL7 Phw Transformer'
          appName: 'phw-hl7transformer'
          appFunctionMidfix: ''
          buildPipeline: 'HL7 Phw Transformer - Build'
          
        - name: 'HL7 Chemo Transformer'
          appName: 'chemo-hl7transformer'
          appFunctionMidfix: ''
          buildPipeline: 'HL7 Chemo Transformer - Build'
          
        - name: 'HL7 Pims Transformer'
          appName: 'pims-hl7transformer'
          appFunctionMidfix: ''
          buildPipeline: 'HL7 Pims Transformer - Build'

        # HL7 Sender Variants
        - name: 'HL7 Sender'
          appName: 'hl7sender'
          appFunctionMidfix: ''
          buildPipeline: 'HL7 Sender - Build'
          
        - name: 'PIMS HL7 Sender'
          appName: 'hl7sender'
          appFunctionMidfix: 'pims'
          buildPipeline: 'HL7 Sender - Build'
          
        - name: 'Chemocare HL7 Sender'
          appName: 'hl7sender'
          appFunctionMidfix: 'chemo'
          buildPipeline: 'HL7 Sender - Build'

        # Mock Receiver
        - name: 'HL7 Mock Receiver'
          appName: 'hl7mockreceiver'
          appFunctionMidfix: ''
          buildPipeline: 'HL7 Mock Receiver - Build'
      
      # Environment configurations
      environments:
        - name: 'dev'
          displayName: 'Development'
          resourceGroup: 'UK-South-DHCW-IntHub-DEV-RG'
          poolName: 'POOL_NAME_NON_PROD'
          dependsOnPrevious: false
          
        - name: 'dte'
          displayName: 'DTE'
          resourceGroup: 'UK-South-DHCW-IntHub-DTE-RG'
          poolName: 'POOL_NAME_NON_PROD'
          dependsOnPrevious: true
          
        - name: 'tst'
          displayName: 'Test'
          resourceGroup: 'UK-South-DHCW-IntHub-TST-RG'
          poolName: 'POOL_NAME_NON_PROD'
          dependsOnPrevious: true
          
        - name: 'ppd'
          displayName: 'Pre-Production'
          resourceGroup: 'UK-South-DHCW-IntHub-PPD-RG'
          poolName: 'POOL_NAME_PROD'
          dependsOnPrevious: true
          
        - name: 'prd'
          displayName: 'Production'
          resourceGroup: 'UK-South-DHCW-IntHub-PRD-RG'
          poolName: 'POOL_NAME_PROD'
          dependsOnPrevious: true
