# Dynamic Stage Generation Template
# This template generates deployment stages for an app across specified environments

parameters:
  - name: appConfig
    type: object
  - name: environments
    type: object
  - name: azureLocation
    type: string
  - name: acrName
    type: string
  - name: azureServiceConnection
    type: string
  - name: selectedApps
    type: string
    default: 'all'
  - name: selectedEnvironments
    type: string
    default: 'all'
  - name: maintainDependencies
    type: boolean
    default: false

stages:
  # Loop through each environment
  - ${{ each env in parameters.environments }}:
    # Check if environment is selected (supports comma-separated list)
    # Deploy if: 'all' is selected OR environment name is in the comma-separated list
    - ${{ if or(eq(parameters.selectedEnvironments, 'all'), contains(parameters.selectedEnvironments, env.name)) }}:
      # Loop through each application
      - ${{ each app in parameters.appConfig }}:
        # Check if app is selected (supports comma-separated list)
        # Deploy if: 'all' is selected OR app name is in the comma-separated list
        - ${{ if or(eq(parameters.selectedApps, 'all'), contains(parameters.selectedApps, app.name)) }}:
          - stage: Release_${{ replace(replace(app.name, ' ', ''), '-', '') }}_${{ upper(env.name) }}
            displayName: 'Release ${{ app.name }} - ${{ env.displayName }}'
            
            # Set up dependencies based on maintainDependencies flag and environment configuration
            # Dependencies are created if:
            # 1. The environment requires dependencies (dependsOnPrevious: true)
            # 2. User wants to maintain dependencies (maintainDependencies: true)
            # 3. The previous environment is also being deployed (checked via contains)
            ${{ if and(eq(env.dependsOnPrevious, true), eq(parameters.maintainDependencies, true)) }}:
              ${{ if eq(env.name, 'dte') }}:
                dependsOn: Release_${{ replace(replace(app.name, ' ', ''), '-', '') }}_DEV
              ${{ elseif eq(env.name, 'tst') }}:
                dependsOn: Release_${{ replace(replace(app.name, ' ', ''), '-', '') }}_DTE
              ${{ elseif eq(env.name, 'ppd') }}:
                dependsOn: Release_${{ replace(replace(app.name, ' ', ''), '-', '') }}_TST
              ${{ elseif eq(env.name, 'prd') }}:
                dependsOn: Release_${{ replace(replace(app.name, ' ', ''), '-', '') }}_PPD
            
            jobs:
              - template: release-container-app-template.yml
                parameters:
                  jobName: Release_${{ replace(replace(app.name, ' ', ''), '-', '') }}_${{ upper(env.name) }}
                  displayName: Release ${{ app.name }} - ${{ env.displayName }}
                  appName: ${{ app.appName }}
                  appFunctionMidfix: ${{ app.appFunctionMidfix }}
                  resourceGroupName: ${{ env.resourceGroup }}
                  azureLocation: ${{ parameters.azureLocation }}
                  environment: ${{ env.name }}
                  acrName: ${{ parameters.acrName }}
                  azureServiceConnection: ${{ parameters.azureServiceConnection }}
                  ${{ if eq(env.poolName, 'POOL_NAME_NON_PROD') }}:
                    POOL_NAME: ${{ variables.POOL_NAME_NON_PROD }}
                  ${{ elseif eq(env.poolName, 'POOL_NAME_PROD') }}:
                    POOL_NAME: ${{ variables.POOL_NAME_PROD }}
                  ${{ else }}:
                    POOL_NAME: 'Azure Pipelines'
                  resourcePipelineName: ${{ app.buildPipeline }}
