parameters:
  azureServiceConnection: '' # Azure Service Connection name
  appName: ''
  resourceGroupName: ''
  azureLocation: ''
  environment: ''
  acrName: ''
  acrRepository: ''
  jobName: ''
  displayName: ''
  POOL_NAME: '' # Pool name for the agent
  resourcePipelineName: '' # Name of the pipeline that builds the image tag artifact

jobs:
- job: ${{ parameters.jobName }}
  displayName: ${{ parameters.displayName }}
  pool:
      ${{ if eq(parameters.POOL_NAME, 'Azure Pipelines') }}:
        vmImage: 'ubuntu-latest'
      ${{ else }}:
        name: ${{ parameters.POOL_NAME }}

  steps:
    - checkout: self
      displayName: 'Checkout Repository'

    - download: ${{ parameters.resourcePipelineName }}
      artifact: imageTag

    - task: AzureCLI@2
      displayName: 'Azure CLI Login'
      inputs:
        azureSubscription: ${{ parameters.azureServiceConnection }}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az --version

    - task: AzureCLI@2
      displayName: 'Update Image Tag'
      inputs:
        azureSubscription: ${{ parameters.azureServiceConnection }}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          set -e
          # Read the image tag and set it as a pipeline variable
          IMAGE_TAG=$(cat "$(Pipeline.Workspace)/${{ parameters.resourcePipelineName }}/imageTag/imageTag.txt")
          echo "Image tag is: $IMAGE_TAG"
          
          # Set the variable for use in subsequent steps
          echo "##vso[task.setvariable variable=IMAGE_TAG]$IMAGE_TAG"

          echo "Adding ${{ parameters.environment }} tag to the image ${{ parameters.acrName }}.azurecr.io/${{ parameters.appName }}:$IMAGE_TAG"
          az acr login --name ${{ parameters.acrName }}
          az acr import \
            --name ${{ parameters.acrName }} \
            --source ${{ parameters.acrName }}.azurecr.io/${{ parameters.appName }}:$IMAGE_TAG \
            --image ${{ parameters.appName }}:${{ parameters.environment }} \
            --force

          echo "Tag ${{ parameters.environment }} added to  ${{ parameters.acrName }}.azurecr.io/${{ parameters.appName }}:$IMAGE_TAG"

    - task: AzureCLI@2
      displayName: 'Update Azure Container App'
      inputs:
        azureSubscription: ${{ parameters.azureServiceConnection }}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          set -e
          # Build the app full name dynamically
          appFullName="${{ parameters.azureLocation }}-${{ parameters.environment }}-${{ parameters.appName }}-ca"
          
          # Use the IMAGE_TAG variable set in the previous step
          echo "Using image tag: $(IMAGE_TAG)"
          
          # Create short revision suffix that complies with Azure Container Apps naming rules
          # Extract just the build ID from IMAGE_TAG
          BUILD_ID=$(echo "$(IMAGE_TAG)" | grep -o '[0-9]\+$' || echo "$(Build.BuildId)")
          TIMESTAMP=$(date -u +"%d%m%y%H%M")  # Timestamp format: DDMMYYHHMM
          
          # Create compliant revision suffix (max ~15 chars to stay under 54 char limit)
          REVISION_SUFFIX="b${BUILD_ID}-${TIMESTAMP}"
          
          # Ensure it starts with letter, contains only lowercase alphanumeric and dashes
          REVISION_SUFFIX=$(echo "$REVISION_SUFFIX" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]//g')
          
          echo "Forcing new revision for $appFullName with image ${{ parameters.acrName }}.azurecr.io/${{ parameters.appName }}:${{ parameters.environment }}"
          echo "Using revision suffix: $REVISION_SUFFIX (build: ${BUILD_ID}, time: ${TIMESTAMP})"
          
          # Create a new revision by copying the current revision with new image
          az containerapp revision copy \
            --name $appFullName \
            --resource-group ${{ parameters.resourceGroupName }} \
            --revision-suffix $REVISION_SUFFIX \
            --image ${{ parameters.acrName }}.azurecr.io/${{ parameters.appName }}:$(IMAGE_TAG)

          echo "$appFullName updated with image ${{ parameters.acrName }}.azurecr.io/${{ parameters.appName }}:$(IMAGE_TAG)"

          
